# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# Uncomment couple lines above if you're using you own specs repository
#source '/path/to/specs.git'
#source 'https://cdn.cocoapods.org/'

target 'SampleApp_CocoaPods' do
  project "SampleApp_CocoaPods"

  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SampleApp_CocoaPods
  pod "ItlyAmplitudePlugin"
  pod "ItlyIterativelyPlugin"
  pod "ItlyJsonSchemaValiadtorPlugin"
  pod "ItlyMixpanelPlugin"
  pod "ItlySegmentPlugin"

end
