# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SampleApp_CocoaPods' do
  project "SampleApp_CocoaPods"

  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SampleApp_CocoaPods
  pod "ItlySdk", :path => '..'
  pod "ItlyAmplitudePlugin", :path => '..'
  pod "ItlyIterativelyPlugin", :path => '..'
  pod "ItlySchemaValidatorPlugin", :path => '..'
  pod "ItlyMixpanelPlugin", :path => '..'
  pod "ItlySegmentPlugin", :path => '..'

end
