name: Test

on: pull_request

jobs:
  test:
    name: Test
    runs-on: macos-10.15
    strategy:
      matrix:
        ruby-version: ["2.7.x"]
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set Xcode 12
        run: |
          sudo xcode-select -switch /Applications/Xcode_12.app
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}

#      - name: Cache Bundle Gems and Cocoapods
#        id: cache-gems-pods
#        uses: actions/cache@v2
#        with:
#          path: |
#            Pods
#            vendor/bundle
#          key: ${{ runner.os }}-ruby-${{ matrix.ruby-version }}-gems-${{ hashFiles('**/Gemfile.lock') }}-pods-${{ hashFiles('**/Podfile.lock') }}
#
#      - name: Install Cocoapods
#        if: steps.cache-gems-pods.outputs.cache-hit != 'true'
#        run: |
#          gem install bundler
#          bundle config path vendor/bundle
#          bundle install
#          pod install
#
#      - name: Validate Podfile
#        run: pod lib lint

      - name: iOS SDK Test
        run: |
          xcodebuild test \
            -workspace Sdk.xcworkspace \
            -scheme ItlySdkTests_iOS \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 11,OS=14.0'

      - name: iOS Schema Validator Test
        run: |
          xcodebuild test \
            -workspace Sdk.xcworkspace \
            -scheme ItlySchemaValidatorPluginTests_iOS \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 11,OS=14.0'

      - name: iOS Iteratively Plugin Test
        run: |
          xcodebuild test \
            -workspace Sdk.xcworkspace \
            -scheme ItlyIterativelyPluginTests_iOS \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 11,OS=14.0'